import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  kernelSidebar: [
    {type: 'autogenerated', dirName: 'kernel'},
  ],
  iamSidebar: [
    {type: 'autogenerated', dirName: 'iam'},
  ],
  hubSidebar: [
    {type: 'autogenerated', dirName: 'hub'},
  ],
  gatewaySidebar: [
    {type: 'autogenerated', dirName: 'gateway'},
  ],
  guidesSidebar: [
    {type: 'autogenerated', dirName: 'guides'},
  ],
};

export default sidebars;